BLAS/LAPACK check
GPAW patch doesn't check if BLAS and LAPACK actually exist, so it might trigger a `AttributeError: 'NoneType' object has no attribute 'split'`