LIBS change to fix Ghostscript ZLIB error
Ghostscript was not compiling due to failing on:
`libpng/1.6.36-GCCcore-8.2.0/lib/libpng16.so.16: undefined reference to inflateValidate@ZLIB_1.2.9'`

needed to add `-L$EBROOTZLIB/lib` to the
`preconfigopts += 'export LIBS="$LIBS -lz" && '`
line